In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2] , [3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [9]:
b = np.matrix(l)

In [10]:
b 

matrix([[1, 2, 3, 4]])

In [11]:
a = [2,3,4]

In [12]:
np.asanyarray(a)

array([2, 3, 4])

In [13]:
b = np.matrix(l)

In [14]:
b

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [16]:
a = np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c = a

In [19]:
c

array([1, 2, 3, 4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
c[0] = 100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [28]:
d = np.copy(a)

In [29]:
d

array([100,   2,   3,   4])

In [30]:
a[1] = 400

In [31]:
a

array([100, 400,   3,   4])

In [32]:
d 

array([100,   2,   3,   4])

In [34]:
np.fromfunction(lambda i ,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction(lambda i , j: i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [37]:
iterable = (i*i for i in range(5))

In [39]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
np.fromstring('234 234' , sep = ' ')

array([234., 234.])

In [42]:
np.fromstring('4,5' , sep = ',')

array([4., 5.])

In [43]:
# Numpy Data Types

In [44]:
l = [2,3,4,5,6]

In [45]:
ar = np.array(l)

In [46]:
ar

array([2, 3, 4, 5, 6])

In [47]:
ar.ndim

1

In [48]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [49]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [52]:
ar.dtype

dtype('int64')

In [53]:
ar2.dtype

dtype('int64')

In [54]:
ar22 = np.array([(1.4 , 45 ,45) , (23,45,66)])

In [55]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [56]:
ar22.dtype

dtype('float64')

In [57]:
range(5)

range(0, 5)

In [58]:
list(range(5))

[0, 1, 2, 3, 4]

In [59]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [60]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [62]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [63]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
ar4 = np.zeros((4,3,4,2))

In [70]:
ar4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [71]:
ar4.ndim

4

In [72]:
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
on = np.ones((2,3,2))

In [80]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [82]:
on +4

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [83]:
on *5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [84]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [85]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.eye((2))

array([[1., 0.],
       [0., 1.]])

In [90]:
np.logspace(2,5,10 , base =2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [92]:
arr = np.random.randn(3,4)

In [93]:
arr

array([[-1.2212156 , -0.84955659, -0.27043996,  0.36556315],
       [ 1.13867456, -0.36510977,  0.85980751, -0.03859707],
       [-1.43193192, -1.07271058,  0.54052778,  2.04898977]])

In [94]:
import pandas as pd

In [96]:
pd.DataFrame(arr)

0         1         2         3
0 -1.221216 -0.849557 -0.270440  0.365563
1  1.138675 -0.365110  0.859808 -0.038597
2 -1.431932 -1.072711  0.540528  2.048990

In [97]:
np.random.rand(3,4)

array([[0.14789625, 0.76273288, 0.15574038, 0.95776249],
       [0.91727621, 0.3161165 , 0.1283028 , 0.66396722],
       [0.31352909, 0.07636217, 0.9554627 , 0.38845247]])

In [100]:
pd.DataFrame(np.random.randint(1,110,(3,4))).to_csv('test.csv')

In [101]:
arr = np.random.rand(3,4)

In [102]:
arr

array([[0.33560441, 0.0327306 , 0.49044096, 0.39860416],
       [0.19831052, 0.38108091, 0.1317547 , 0.1706358 ],
       [0.74137836, 0.28456772, 0.5740742 , 0.9161728 ]])

In [103]:
arr.reshape(6,2)

array([[0.33560441, 0.0327306 ],
       [0.49044096, 0.39860416],
       [0.19831052, 0.38108091],
       [0.1317547 , 0.1706358 ],
       [0.74137836, 0.28456772],
       [0.5740742 , 0.9161728 ]])

In [104]:
arr.reshape(3,4)

array([[0.33560441, 0.0327306 , 0.49044096, 0.39860416],
       [0.19831052, 0.38108091, 0.1317547 , 0.1706358 ],
       [0.74137836, 0.28456772, 0.5740742 , 0.9161728 ]])

In [107]:
arr.reshape(4,3)

array([[0.33560441, 0.0327306 , 0.49044096],
       [0.39860416, 0.19831052, 0.38108091],
       [0.1317547 , 0.1706358 , 0.74137836],
       [0.28456772, 0.5740742 , 0.9161728 ]])

In [108]:
arr1 = arr.reshape(6,2)

In [109]:
arr1

array([[0.33560441, 0.0327306 ],
       [0.49044096, 0.39860416],
       [0.19831052, 0.38108091],
       [0.1317547 , 0.1706358 ],
       [0.74137836, 0.28456772],
       [0.5740742 , 0.9161728 ]])

In [110]:
arr1[1][1]

0.39860416217674477

In [112]:
arr1[2:5][1]

array([0.1317547, 0.1706358])

In [114]:
arr = np.random.randint(1,100,(5,5))

In [116]:
arr

array([[58, 88, 91, 37, 96],
       [94,  2, 76,  1, 26],
       [41, 84, 86, 52, 35],
       [ 3, 51, 98, 57, 54],
       [21, 33, 78, 32, 44]])

In [118]:
arr[arr > 50]

array([58, 88, 91, 96, 94, 76, 84, 86, 52, 51, 98, 57, 54, 78])

In [119]:
arr

array([[58, 88, 91, 37, 96],
       [94,  2, 76,  1, 26],
       [41, 84, 86, 52, 35],
       [ 3, 51, 98, 57, 54],
       [21, 33, 78, 32, 44]])

In [120]:
arr[2:4,[1,2]]

array([[84, 86],
       [51, 98]])

In [121]:
arr[0][0] = 5000

In [122]:
arr

array([[5000,   88,   91,   37,   96],
       [  94,    2,   76,    1,   26],
       [  41,   84,   86,   52,   35],
       [   3,   51,   98,   57,   54],
       [  21,   33,   78,   32,   44]])

In [126]:
arr[3:5,[2,4]]

array([[98, 54],
       [78, 44]])

In [127]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [129]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [130]:
arr2

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [131]:
arr1 +arr2

array([[3, 3, 4],
       [3, 4, 3],
       [2, 2, 4]])

In [132]:
arr1 -arr2

array([[-1,  1,  0],
       [-1,  0, -1],
       [ 0,  0,  0]])

In [133]:
arr1*arr2

array([[2, 2, 4],
       [2, 4, 2],
       [1, 1, 4]])

In [135]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [1, 1, 2]])

In [136]:
arr2

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [139]:
arr1@arr2

array([[ 8,  7, 10],
       [ 7,  6,  8],
       [ 6,  5,  8]])

In [140]:
arr1/0

/tmp/ipykernel_3875/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [141]:
arr1 + 100

array([[101, 102, 102],
       [101, 102, 101],
       [101, 101, 102]])

In [142]:
arr1 **2

array([[1, 4, 4],
       [1, 4, 1],
       [1, 1, 4]])

In [143]:
# Numpy Brodcasting

In [158]:
arr= np.zeros((4,4))

In [163]:
row = np.array([1,2,3,4])

In [160]:
row

array([1, 2, 3, 4])

In [162]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [164]:
row.shape

(4,)

In [165]:
row.T

array([1, 2, 3, 4])

In [167]:
col = np.array([[1,2,3,4]])

In [168]:
col

array([[1, 2, 3, 4]])

In [169]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [170]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [172]:
arr1  = np.random.randint(1,4,(3,4))

In [173]:
arr1

array([[1, 1, 1, 3],
       [2, 2, 1, 1],
       [2, 3, 3, 1]])

In [174]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        , 1.73205081],
       [1.41421356, 1.41421356, 1.        , 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.        ]])

In [175]:
np.log10(arr1)

array([[0.        , 0.        , 0.        , 0.47712125],
       [0.30103   , 0.30103   , 0.        , 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.        ]])

In [178]:
arr = np.random.randint(2,10 ,(3,4))

In [179]:
arr

array([[7, 9, 6, 8],
       [9, 2, 9, 4],
       [9, 5, 2, 6]])

In [180]:
arr.reshape(6,2)

array([[7, 9],
       [6, 8],
       [9, 2],
       [9, 4],
       [9, 5],
       [2, 6]])

In [182]:
arr.reshape(2,6)

array([[7, 9, 6, 8, 9, 2],
       [9, 4, 9, 5, 2, 6]])

In [183]:
arr.T

array([[7, 9, 9],
       [9, 2, 5],
       [6, 9, 2],
       [8, 4, 6]])

In [184]:
arr

array([[7, 9, 6, 8],
       [9, 2, 9, 4],
       [9, 5, 2, 6]])

In [185]:
arr.flatten()

array([7, 9, 6, 8, 9, 2, 9, 4, 9, 5, 2, 6])

In [187]:
arr.ndim

2

In [188]:
arr1 = np.array([1,2,3,3,4])

In [189]:
arr1

array([1, 2, 3, 3, 4])

In [190]:
arr1.ndim

1

In [191]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [192]:
np.expand_dims(arr1,axis = 0)

array([[1, 2, 3, 3, 4]])

In [193]:
arr


array([[7, 9, 6, 8],
       [9, 2, 9, 4],
       [9, 5, 2, 6]])

In [195]:
np.squeeze(arr)

array([[7, 9, 6, 8],
       [9, 2, 9, 4],
       [9, 5, 2, 6]])

In [196]:
data = np.array([[1] , [2] , [3]])

In [197]:
data

array([[1],
       [2],
       [3]])

In [198]:
np.squeeze(data)

array([1, 2, 3])

In [199]:
arr1

array([1, 2, 3, 3, 4])

In [200]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [202]:
np.roll(arr1 ,2)

array([3, 4, 1, 2, 3])

In [203]:
arr1


array([1, 2, 3, 3, 4])

In [204]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [205]:
# Numpy Binary operation

In [206]:
arr1 = np.random.randint(1,10 , (3,4))

In [207]:
arr1

array([[8, 6, 8, 1],
       [4, 2, 8, 6],
       [7, 9, 8, 9]])

In [209]:
arr1 + arr

array([[15, 15, 14,  9],
       [13,  4, 17, 10],
       [16, 14, 10, 15]])

In [211]:
arr1 - arr

array([[ 1, -3,  2, -7],
       [-5,  0, -1,  2],
       [-2,  4,  6,  3]])

In [213]:
arr1%arr

array([[1, 6, 2, 1],
       [4, 0, 8, 2],
       [7, 4, 0, 3]])

In [215]:
arr1 ** arr

array([[  2097152,  10077696,    262144,         1],
       [   262144,         4, 134217728,      1296],
       [ 40353607,     59049,        64,    531441]])

In [217]:
arr1 & arr

array([[0, 0, 0, 0],
       [0, 2, 8, 4],
       [1, 1, 0, 0]])

In [221]:
arr1|arr

array([[15, 15, 14,  9],
       [13,  2,  9,  6],
       [15, 13, 10, 15]])

In [225]:
o = np.array(["tabraiz" , "imam"])

In [226]:
o

array(['tabraiz', 'imam'], dtype='<U7')

In [227]:
np.char.upper(o)

array(['TABRAIZ', 'IMAM'], dtype='<U7')

In [228]:
np.char.title(o)

array(['Tabraiz', 'Imam'], dtype='<U7')

In [229]:
arr1

array([[8, 6, 8, 1],
       [4, 2, 8, 6],
       [7, 9, 8, 9]])

In [ ]:
np.sin(arr1)